### ISSUE TITLE
is this best cross platform approach to streaming protobuf?

### ISSUE THREAD

**Issue by dominictarr** [mafintosh/pbs#8]
In this module you encode the stream as essentially a message type with a single repeated field.  This is nice because you can decode the entire thing as a static file with any protobuf library.

I've seen others just frame the top level message in the stream with a single varint for length. That's not too tricky but now the stream is not valid protobuf.
Your form isn't much more complicated than that, it's just two varints, the first is fixed  `field_num << 3 | 2` (the 2 means a length delimited tag) and then `length`. If the field_num is under 16 then it's only one additional byte.

But is this a format that is easy to stream in other languages?

**Comment by mafintosh** [comment]
Yea (unfortunately) they didn't really specifiy a streaming format, but refer to grpc instead with is http2.

I never ended up using this in practice, but I liked for the same reasons you describe.

**Comment by dominictarr** [comment]
ah, okay thanks. protobuf seems like a good start but seems to really be falling slightly short here, and http2 isn't aways available...
